"""Add foreign key to reviews

Revision ID: 112e60fa4ccc
Revises: 9f587347a9d3
Create Date: 2024-07-08 12:48:28.246195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '112e60fa4ccc'
down_revision = '9f587347a9d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reviews', sa.Column('employee_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_reviews_employee_id_employees'), 'reviews', 'employees', ['employee_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_reviews_employee_id_employees'), 'reviews', type_='foreignkey')
    op.drop_column('reviews', 'employee_id')
    # ### end Alembic commands ###
